<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPPVZKmu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPPVZKmu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPPVZKmu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPPVZKmu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPPVZKmu\App_KernelDevDebugContainer([
    'container.build_hash' => 'PPVZKmu',
    'container.build_id' => '90efd65a',
    'container.build_time' => 1719307634,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPPVZKmu');
